<a href="https://colab.research.google.com/github/valsorayksterob/interlink/blob/main/interlink.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/1.0_day.csv')
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2022-06-21T12:50:02.530Z,19.212667,-155.379166,31.360001,2.39,ml,42.0,166.0,NaN,0.13,...,2022-06-21T12:55:32.580Z,"10 km E of P훮hala, Hawaii",earthquake,0.59,0.92,4.100000,5.0,automatic,hv,hv
1,2022-06-21T12:42:14.572Z,63.181500,-151.141200,0.000000,1.80,ml,NaN,NaN,NaN,0.71,...,2022-06-21T12:45:06.507Z,"49 km SE of Denali National Park, Alaska",earthquake,NaN,0.30,NaN,NaN,automatic,ak,ak
2,2022-06-21T12:10:29.550Z,19.188168,-155.387833,32.830002,1.75,md,41.0,164.0,NaN,0.11,...,2022-06-21T12:13:38.860Z,"9 km E of P훮hala, Hawaii",earthquake,0.62,0.78,0.870000,3.0,automatic,hv,hv
3,2022-06-21T11:59:47.271Z,18.474200,-73.891500,10.000000,4.10,mb,NaN,71.0,1.72200,0.22,...,2022-06-21T12:48:28.040Z,"10 km S of Corail, Haiti",earthquake,2.90,1.90,0.123000,18.0,reviewed,us,us
4,2022-06-21T11:23:02.244Z,26.701200,126.446200,10.000000,4.60,mb,NaN,40.0,1.63800,0.62,...,2022-06-21T11:56:09.040Z,"134 km WNW of Naha, Japan",earthquake,6.60,1.90,0.070000,61.0,reviewed,us,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,2022-06-20T13:19:35.950Z,34.137333,-116.879500,29.780000,0.96,ml,12.0,188.0,0.21600,0.18,...,2022-06-20T13:23:15.592Z,"12km SSE of Big Bear Lake, CA",earthquake,0.78,0.60,0.254000,15.0,automatic,ci,ci
190,2022-06-20T13:09:21.730Z,38.779335,-122.768333,1.270000,1.13,md,6.0,98.0,0.03552,0.03,...,2022-06-20T15:30:10.659Z,"1km WNW of The Geysers, CA",earthquake,0.38,1.15,0.170000,6.0,automatic,nc,nc
191,2022-06-20T13:07:49.290Z,54.570167,-163.331833,8.860000,1.35,ml,4.0,272.0,NaN,0.13,...,2022-06-21T01:00:42.450Z,"32 km S of False Pass, Alaska",earthquake,0.82,0.71,0.420979,4.0,reviewed,av,av
192,2022-06-20T13:07:49.090Z,37.341833,-121.767333,7.290000,1.38,md,27.0,58.0,0.03102,0.10,...,2022-06-20T20:11:26.338Z,"6km ESE of Alum Rock, CA",earthquake,0.25,0.38,0.169000,21.0,reviewed,nc,nc
193,2022-06-20T13:04:11.090Z,19.242666,-155.398834,32.419998,2.15,ml,42.0,135.0,NaN,0.13,...,2022-06-20T13:09:41.980Z,"9 km ENE of P훮hala, Hawaii",earthquake,0.51,0.60,4.020000,4.0,automatic,hv,hv